# Generated by Django 2.0.2 on 2018-03-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssig_site_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(to='base.Group'),
        ),
    ]
