# Generated by Django 2.0.2 on 2018-03-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_event_group'),
        ('ssig_site_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interest_groups',
            field=models.ManyToManyField(to='base.Group'),
        ),
    ]
