# Generated by Django 2.0.2 on 2018-03-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_event'),
        ('ssig_site_auth', '0002_auto_20180305_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interest_groups',
            field=models.ManyToManyField(to='base.Group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
    ]
