# Generated by Django 2.0.2 on 2018-03-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_event_group'),
        ('ssig_site_auth', '0002_user_interest_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interest_events',
            field=models.ManyToManyField(to='base.Event'),
        ),
    ]
