# Generated by Django 2.0.2 on 2018-03-10 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssig_site_auth', '0003_user_interest_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='interest_events',
            new_name='events',
        ),
    ]
