# Generated by Django 2.0.2 on 2018-04-22 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssig_site_auth', '0005_remove_user_interest_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='events',
        ),
    ]
