# Generated by Django 2.0.2 on 2018-03-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_event_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='Somewhere', max_length=200),
            preserve_default=False,
        ),
    ]
