# Generated by Django 2.0.2 on 2018-03-15 16:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20180315_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupuser',
            name='status',
        ),
        migrations.AddField(
            model_name='groupuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupuser',
            name='role',
            field=models.CharField(choices=[('l', 'Leader'), ('m', 'Member')], default='m', max_length=2),
        ),
    ]
