# Generated by Django 2.0.2 on 2018-03-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20180315_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='short_description',
        ),
        migrations.AddField(
            model_name='event',
            name='long_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
