# Generated by Django 2.0.2 on 2018-04-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20180322_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.DecimalField(decimal_places=5, default=51.523, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.DecimalField(decimal_places=5, default=-0.132, max_digits=8),
            preserve_default=False,
        ),
    ]
