# Generated by Django 2.0.2 on 2018-04-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20180422_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='restricted_to',
            field=models.CharField(blank=True, choices=[('m', 'Group Members'), ('s', 'UCL Students and Staff'), ('', 'Public')], default='s', max_length=2),
        ),
    ]
